name: Terraform Feature CI

on:
  push:
    branches:
      - "feature/**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Init Plan Scan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Enviroment/prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
         working-directory: ./Enviroment/prod

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -var-file="terraform.tfvars"
        working-directory: ./Enviroment/prod

      - name: Terraform Security Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: Enviroment/prod