name: Terraform Feature CI

on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Init Plan Scan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Enviroment/prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform files
        run: |
          pwd
          ls -la

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Debug Terraform files
  run: |
    echo "Current directory:"
    pwd
    echo "Files:"
    ls -la
    echo "Terraform files:"
    find . -maxdepth 2 -type f -print

      - name: Terraform Plan
  run: terraform plan -input=false -var-file="./terraform.tfvars"

      - name: Terraform Security Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: Enviroment/prod